[build]
  command = "yarn build"
  functions = "build/functions/"
  publish = "build/app/"

[dev]
  command = "yarn run-p start:**"
  targetPort = 8080
  publish = "build/app/"
  framework = "#custom"